services:
  backend:
    build: ./backend
    image: izabela/task-manager-backend:latest
    container_name: task-manager-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taskdb
      DB_USER: postgres
      DB_PASSWORD: postgres

  telegram-bot:
    build: ./telegram-bot
    image: izabela/olx-listing-bot:latest
    container_name: olx-listing-bot
    env_file:
      - ./telegram-bot/.env
    restart: unless-stopped

  note-bot:
    build: ./note-bot
    image: izabela/note-bot:latest
    container_name: note-bot
    env_file:
      - ./note-bot/.env
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:16
    container_name: task-manager-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: